Repository hashicorp/consul-helm, pull requests merged in 2019-10, with the labels that each got.

#250 Run server-acl-init even when clients are disabled
  templates/server-acl-init-cleanup-clusterrole.yaml
  templates/server-acl-init-cleanup-clusterrolebinding.yaml
  templates/server-acl-init-cleanup-job.yaml
  templates/server-acl-init-cleanup-serviceaccount.yaml
  templates/server-acl-init-clusterrole.yaml
  templates/server-acl-init-clusterrolebinding.yaml
  templates/server-acl-init-job.yaml
  templates/server-acl-init-serviceaccount.yaml
  test/unit/server-acl-init-cleanup-clusterrole.bats
  test/unit/server-acl-init-cleanup-clusterrolebinding.bats
  test/unit/server-acl-init-cleanup-job.bats
  test/unit/server-acl-init-cleanup-serviceaccount.bats
  test/unit/server-acl-init-clusterrole.bats
  test/unit/server-acl-init-clusterrolebinding.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-acl-init-serviceaccount.bats
Labels: area/acls, enhancement, theme/no-clients

#247 Fix docs copy-paste mistake
  values.yaml
Labels: area/chart-only

#248 Less privileges when syncCatalog.toK8S = false
  templates/sync-catalog-clusterrole.yaml
  test/unit/sync-catalog-clusterrole.bats
Labels: area/chart-only, enhancement

#249 Add flag for turning off tests
  templates/tests/test-runner.yaml
  test/unit/test-runner.bats
  values.yaml
Labels: area/chart-only, enhancement

#266 Fix to retry join not populating with helm 2.15.0
  templates/server-statefulset.yaml
  test/unit/client-daemonset.bats
  test/unit/server-statefulset.bats
Labels: waiting-on-response
