Repository hashicorp/consul-helm, pull requests merged in 2020-01, with the labels that each got.

#320 Update test-runner.yaml
  templates/tests/test-runner.yaml
Labels: area/chart-only, enhancement

#313 Enable TLS
  CHANGELOG.md
  templates/client-daemonset.yaml
  templates/client-podsecuritypolicy.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-deployment.yaml
  templates/enterprise-license-job.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-acl-init-job.yaml
  templates/server-service.yaml
  templates/server-statefulset.yaml
  templates/sync-catalog-deployment.yaml
  templates/tests/test-runner.yaml
  templates/tls-init-cleanup-clusterrole.yaml
  templates/tls-init-cleanup-clusterrolebinding.yaml
  templates/tls-init-cleanup-job.yaml
  templates/tls-init-cleanup-podsecuritypolicy.yaml
  templates/tls-init-cleanup-serviceaccount.yaml
  templates/tls-init-clusterrole.yaml
  templates/tls-init-clusterrolebinding.yaml
  templates/tls-init-job.yaml
  templates/tls-init-podsecuritypolicy.yaml
  templates/tls-init-serviceaccount.yaml
  templates/ui-service.yaml
  test/unit/client-daemonset.bats
  test/unit/client-podsecuritypolicy.bats
  test/unit/client-snapshot-agent-deployment.bats
  test/unit/connect-inject-deployment.bats
  test/unit/enterprise-license-job.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-clusterrole.bats
  test/unit/server-service.bats
  test/unit/server-statefulset.bats
  test/unit/sync-catalog-deployment.bats
  test/unit/tls-init-cleanup-clusterrole.bats
  test/unit/tls-init-cleanup-clusterrolebinding.bats
  test/unit/tls-init-cleanup-job.bats
  test/unit/tls-init-cleanup-podsecuritypolicy.bats
  test/unit/tls-init-cleanup-serviceaccount.bats
  test/unit/tls-init-clusterrole.bats
  test/unit/tls-init-clusterrolebinding.bats
  test/unit/tls-init-job.bats
  test/unit/tls-init-podsecuritypolicy.bats
  test/unit/tls-init-serviceaccount.bats
  test/unit/ui-service.bats
  values.yaml
Labels: enhancement, theme/tls

#317 Add namespace support to the connect injector
  templates/connect-inject-deployment.yaml
  templates/enterprise-license-job.yaml
  test/unit/connect-inject-deployment.bats
  values.yaml
Labels: enhancement, theme/consul-namespaces

#337 Add sync catalog Consul namespace support to the Helm chart
  templates/sync-catalog-deployment.yaml
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: enhancement, theme/consul-namespaces

#341 Add namespace support for the acl bootstrapping job
  templates/server-acl-init-job.yaml
  test/unit/server-acl-init-job.bats
Labels: enhancement, theme/consul-namespaces
