Repository hashicorp/consul-helm, pull requests merged in 2020-11, with the labels that each got.

#665 ACL support for health checks controller
  templates/connect-inject-clusterrole.yaml
  templates/connect-inject-deployment.yaml
  templates/server-acl-init-job.yaml
  test/acceptance/tests/connect/health_checks_test.go
  test/unit/connect-inject-clusterrole.bats
  test/unit/connect-inject-deployment.bats
  test/unit/server-acl-init-job.bats
Labels: area/acls, enhancement, theme/health-checks

#673 pass health checks controller flag only when enabled
  templates/connect-inject-deployment.yaml
  test/unit/connect-inject-deployment.bats
Labels: bug, theme/health-checks

#677 Add acceptance tests for health checks on consul-ent
  .circleci/config.yml
  test/acceptance/helpers/helpers.go
  test/acceptance/tests/connect/health_checks_namespaces_test.go
  test/acceptance/tests/connect/health_checks_test.go
Labels: theme/acceptance-tests, theme/consul-namespaces, theme/health-checks

#679 circleci: Increase no_output_timeout for openshift tests
  .circleci/config.yml
Labels: area/builds

#681 update values file comments for health checks and enable health checks by default
  test/unit/connect-inject-clusterrole.bats
  test/unit/connect-inject-deployment.bats
  values.yaml
Labels: theme/health-checks

#688 Run acceptance tests against aks 1.19 nightly
  .circleci/config.yml
  test/terraform/aks/main.tf
  test/terraform/aks/outputs.tf
  test/terraform/aks/variables.tf
Labels: theme/acceptance-tests

#701 acceptance-tests: use new logger with timestamps everywhere
  test/acceptance/framework/k8s/debug.go
  test/acceptance/tests/connect/connect_inject_namespaces_test.go
  test/acceptance/tests/controller/controller_namespaces_test.go
  test/acceptance/tests/controller/controller_test.go
Labels: theme/acceptance-tests
