Repository hashicorp/consul-helm, pull requests merged in 2020-04, with the labels that each got.

#405 Use auto-encrypt CA volume for service-init when auto-encrypt is enabled
  templates/client-daemonset.yaml
  templates/mesh-gateway-deployment.yaml
Labels: theme/federation

#382 Deprecate bootstrapACLs for acls.enabled
  templates/NOTES.txt
  templates/client-clusterrole.yaml
  templates/client-daemonset.yaml
  templates/client-snapshot-agent-clusterrole.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-authmethod-clusterrole.yaml
  templates/connect-inject-authmethod-clusterrolebinding.yaml
  templates/connect-inject-authmethod-serviceaccount.yaml
  templates/connect-inject-clusterrole.yaml
  templates/connect-inject-deployment.yaml
  templates/enterprise-license-clusterrole.yaml
  templates/enterprise-license-job.yaml
  templates/mesh-gateway-clusterrole.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-acl-init-cleanup-clusterrole.yaml
  templates/server-acl-init-cleanup-clusterrolebinding.yaml
  templates/server-acl-init-cleanup-job.yaml
  templates/server-acl-init-cleanup-podsecuritypolicy.yaml
  templates/server-acl-init-cleanup-serviceaccount.yaml
  templates/server-acl-init-clusterrole.yaml
  templates/server-acl-init-clusterrolebinding.yaml
  templates/server-acl-init-job.yaml
  templates/server-acl-init-podsecuritypolicy.yaml
  templates/server-acl-init-serviceaccount.yaml
  templates/server-config-configmap.yaml
  templates/sync-catalog-clusterrole.yaml
  templates/sync-catalog-deployment.yaml
  test/unit/client-clusterrole.bats
  test/unit/client-daemonset.bats
  test/unit/client-snapshot-agent-clusterrole.bats
  test/unit/client-snapshot-agent-deployment.bats
  test/unit/connect-inject-authmethod-clusterrole.bats
  test/unit/connect-inject-authmethod-clusterrolebinding.bats
  test/unit/connect-inject-authmethod-serviceaccount.bats
  test/unit/connect-inject-clusterrole.bats
  test/unit/connect-inject-deployment.bats
  test/unit/enterprise-license-clusterrole.bats
  test/unit/enterprise-license-job.bats
  test/unit/helpers.bats
  test/unit/mesh-gateway-clusterrole.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/server-acl-init-cleanup-clusterrole.bats
  test/unit/server-acl-init-cleanup-clusterrolebinding.bats
  test/unit/server-acl-init-cleanup-job.bats
  test/unit/server-acl-init-cleanup-podsecuritypolicy.bats
  test/unit/server-acl-init-cleanup-serviceaccount.bats
  test/unit/server-acl-init-clusterrole.bats
  test/unit/server-acl-init-clusterrolebinding.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-acl-init-podsecuritypolicy.bats
  test/unit/server-acl-init-serviceaccount.bats
  test/unit/server-configmap.bats
  test/unit/sync-catalog-clusterrole.bats
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: area/multi-dc, enhancement

#407 Run enterprise-license job on upgrades
  CHANGELOG.md
  templates/enterprise-license-job.yaml
  values.yaml
Labels: area/chart-only, enhancement

#374 ACL Replication
  CHANGELOG.md
  templates/NOTES.txt
  templates/client-clusterrole.yaml
  templates/client-daemonset.yaml
  templates/client-snapshot-agent-clusterrole.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-authmethod-clusterrole.yaml
  templates/connect-inject-authmethod-clusterrolebinding.yaml
  templates/connect-inject-authmethod-serviceaccount.yaml
  templates/connect-inject-clusterrole.yaml
  templates/connect-inject-deployment.yaml
  templates/enterprise-license-clusterrole.yaml
  templates/enterprise-license-job.yaml
  templates/mesh-gateway-clusterrole.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-acl-init-cleanup-clusterrole.yaml
  templates/server-acl-init-cleanup-clusterrolebinding.yaml
  templates/server-acl-init-cleanup-job.yaml
  templates/server-acl-init-cleanup-podsecuritypolicy.yaml
  templates/server-acl-init-cleanup-serviceaccount.yaml
  templates/server-acl-init-clusterrole.yaml
  templates/server-acl-init-clusterrolebinding.yaml
  templates/server-acl-init-job.yaml
  templates/server-acl-init-podsecuritypolicy.yaml
  templates/server-acl-init-serviceaccount.yaml
  templates/server-config-configmap.yaml
  templates/server-statefulset.yaml
  templates/sync-catalog-clusterrole.yaml
  templates/sync-catalog-deployment.yaml
  templates/tls-init-job.yaml
  test/unit/client-clusterrole.bats
  test/unit/client-daemonset.bats
  test/unit/client-snapshot-agent-clusterrole.bats
  test/unit/client-snapshot-agent-deployment.bats
  test/unit/connect-inject-authmethod-clusterrole.bats
  test/unit/connect-inject-authmethod-clusterrolebinding.bats
  test/unit/connect-inject-authmethod-serviceaccount.bats
  test/unit/connect-inject-clusterrole.bats
  test/unit/connect-inject-deployment.bats
  test/unit/enterprise-license-clusterrole.bats
  test/unit/enterprise-license-job.bats
  test/unit/helpers.bats
  test/unit/mesh-gateway-clusterrole.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/mesh-gateway-service.bats
  test/unit/server-acl-init-cleanup-clusterrole.bats
  test/unit/server-acl-init-cleanup-clusterrolebinding.bats
  test/unit/server-acl-init-cleanup-job.bats
  test/unit/server-acl-init-cleanup-podsecuritypolicy.bats
  test/unit/server-acl-init-cleanup-serviceaccount.bats
  test/unit/server-acl-init-clusterrole.bats
  test/unit/server-acl-init-clusterrolebinding.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-acl-init-podsecuritypolicy.bats
  test/unit/server-acl-init-serviceaccount.bats
  test/unit/server-configmap.bats
  test/unit/server-statefulset.bats
  test/unit/sync-catalog-clusterrole.bats
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: area/multi-dc, enhancement

#417 Use /home/consul-k8s as working dir
  templates/mesh-gateway-deployment.yaml
  test/unit/mesh-gateway-deployment.bats
Labels: area/chart-only, enhancement

#411 Image pull secrets
  CHANGELOG.md
  templates/client-serviceaccount.yaml
  templates/client-snapshot-agent-serviceaccount.yaml
  templates/connect-inject-authmethod-serviceaccount.yaml
  templates/connect-inject-serviceaccount.yaml
  templates/enterprise-license-serviceaccount.yaml
  templates/mesh-gateway-serviceaccount.yaml
  templates/server-acl-init-cleanup-serviceaccount.yaml
  templates/server-acl-init-serviceaccount.yaml
  templates/server-serviceaccount.yaml
  templates/sync-catalog-serviceaccount.yaml
  templates/tls-init-cleanup-serviceaccount.yaml
  templates/tls-init-serviceaccount.yaml
  test/unit/client-serviceaccount.bats
  test/unit/client-snapshot-agent-serviceaccount.bats
  test/unit/connect-inject-authmethod-serviceaccount.bats
  test/unit/connect-inject-serviceaccount.bats
  test/unit/enterprise-license-serviceaccount.bats
  test/unit/mesh-gateway-serviceaccount.bats
  test/unit/server-acl-init-cleanup-serviceaccount.bats
  test/unit/server-acl-init-serviceaccount.bats
  test/unit/server-serviceaccount.bats
  test/unit/sync-catalog-serviceaccount.bats
  test/unit/tls-init-cleanup-serviceaccount.bats
  test/unit/tls-init-serviceaccount.bats
  values.yaml
Labels: area/chart-only, enhancement

#419 tls-init-cleanup can run if pre-install fails
  templates/tls-init-cleanup-clusterrole.yaml
  templates/tls-init-cleanup-clusterrolebinding.yaml
  templates/tls-init-cleanup-job.yaml
  templates/tls-init-cleanup-podsecuritypolicy.yaml
  templates/tls-init-cleanup-serviceaccount.yaml
  templates/tls-init-job.yaml
Labels: area/chart-only, bug

#401 Provide server stateful set DNS names to the ACL init job
  templates/server-acl-init-job.yaml
  test/unit/helpers.bats
  test/unit/server-acl-init-job.bats
  values.yaml
Labels: area/acls, enhancement

#420 ACLs: Support external servers
  templates/server-acl-init-cleanup-clusterrole.yaml
  templates/server-acl-init-cleanup-clusterrolebinding.yaml
  templates/server-acl-init-cleanup-job.yaml
  templates/server-acl-init-cleanup-podsecuritypolicy.yaml
  templates/server-acl-init-cleanup-serviceaccount.yaml
  templates/server-acl-init-clusterrole.yaml
  templates/server-acl-init-clusterrolebinding.yaml
  templates/server-acl-init-job.yaml
  templates/server-acl-init-podsecuritypolicy.yaml
  templates/server-acl-init-serviceaccount.yaml
  test/unit/helpers.bats
  test/unit/server-acl-init-cleanup-clusterrole.bats
  test/unit/server-acl-init-cleanup-clusterrolebinding.bats
  test/unit/server-acl-init-cleanup-job.bats
  test/unit/server-acl-init-cleanup-podsecuritypolicy.bats
  test/unit/server-acl-init-cleanup-serviceaccount.bats
  test/unit/server-acl-init-clusterrole.bats
  test/unit/server-acl-init-clusterrolebinding.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-acl-init-podsecuritypolicy.bats
  test/unit/server-acl-init-serviceaccount.bats
  values.yaml
Labels: area/acls, theme/external-servers

#430 Reorganize externalServers section
  templates/_helpers.tpl
  templates/client-daemonset.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-deployment.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-acl-init-cleanup-podsecuritypolicy.yaml
  templates/server-acl-init-clusterrole.yaml
  templates/server-acl-init-job.yaml
  templates/sync-catalog-deployment.yaml
  templates/tests/test-runner.yaml
  test/unit/client-daemonset.bats
  test/unit/client-snapshot-agent-deployment.bats
  test/unit/connect-inject-deployment.bats
  test/unit/helpers.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/server-acl-init-cleanup-clusterrole.bats
  test/unit/server-acl-init-cleanup-clusterrolebinding.bats
  test/unit/server-acl-init-cleanup-job.bats
  test/unit/server-acl-init-cleanup-podsecuritypolicy.bats
  test/unit/server-acl-init-cleanup-serviceaccount.bats
  test/unit/server-acl-init-clusterrole.bats
  test/unit/server-acl-init-clusterrolebinding.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-acl-init-podsecuritypolicy.bats
  test/unit/server-acl-init-serviceaccount.bats
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: theme/external-servers

#427 ACLs: support external servers meta PR
  CHANGELOG.md
  scripts/generate-helm-config-for-hcs.sh
  templates/_helpers.tpl
  templates/client-daemonset.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-deployment.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-acl-init-cleanup-clusterrole.yaml
  templates/server-acl-init-cleanup-clusterrolebinding.yaml
  templates/server-acl-init-cleanup-job.yaml
  templates/server-acl-init-cleanup-podsecuritypolicy.yaml
  templates/server-acl-init-cleanup-serviceaccount.yaml
  templates/server-acl-init-clusterrole.yaml
  templates/server-acl-init-clusterrolebinding.yaml
  templates/server-acl-init-job.yaml
  templates/server-acl-init-podsecuritypolicy.yaml
  templates/server-acl-init-serviceaccount.yaml
  templates/sync-catalog-deployment.yaml
  templates/tests/test-runner.yaml
  test/unit/client-daemonset.bats
  test/unit/client-snapshot-agent-deployment.bats
  test/unit/connect-inject-deployment.bats
  test/unit/helpers.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/server-acl-init-cleanup-clusterrole.bats
  test/unit/server-acl-init-cleanup-clusterrolebinding.bats
  test/unit/server-acl-init-cleanup-job.bats
  test/unit/server-acl-init-cleanup-podsecuritypolicy.bats
  test/unit/server-acl-init-cleanup-serviceaccount.bats
  test/unit/server-acl-init-clusterrole.bats
  test/unit/server-acl-init-clusterrolebinding.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-acl-init-podsecuritypolicy.bats
  test/unit/server-acl-init-serviceaccount.bats
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: area/acls, theme/external-servers

#435 client.join and externalServers.hosts can accept cloud auto-join with spaces
  templates/client-daemonset.yaml
  templates/server-acl-init-job.yaml
  test/unit/client-daemonset.bats
  test/unit/helpers.bats
  test/unit/server-acl-init-job.bats
Labels: theme/external-servers
