Repository hashicorp/consul-helm, pull requests merged in 2020-03, with the labels that each got.

#348 Apply license until success
  templates/enterprise-license-job.yaml
Labels: bug

#346 Allow setting your own CA as a kube secret
  templates/client-daemonset.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-deployment.yaml
  templates/enterprise-license-job.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-acl-init-job.yaml
  templates/server-statefulset.yaml
  templates/sync-catalog-deployment.yaml
  templates/tests/test-runner.yaml
  templates/tls-init-cleanup-clusterrole.yaml
  templates/tls-init-cleanup-job.yaml
  templates/tls-init-job.yaml
  test/unit/client-daemonset.bats
  test/unit/client-snapshot-agent-deployment.bats
  test/unit/connect-inject-deployment.bats
  test/unit/enterprise-license-job.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/server-acl-init-job.bats
  test/unit/server-statefulset.bats
  test/unit/sync-catalog-deployment.bats
  test/unit/tls-init-job.bats
  values.yaml
Labels: enhancement, theme/tls

#369 helm3 support for NOTES.txt
  templates/NOTES.txt
Labels: area/chart-only, documentation, waiting-on-response

#376 Add custom annotation for service
  templates/server-service.yaml
  test/unit/server-service.bats
  values.yaml
Labels: area/chart-only, enhancement, waiting-on-response

#368 Support ACL replication.
  templates/server-acl-init-job.yaml
  templates/server-config-configmap.yaml
  templates/server-statefulset.yaml
  test/unit/server-acl-init-job.bats
  test/unit/server-configmap.bats
  test/unit/server-statefulset.bats
  values.yaml
Labels: area/multi-dc, enhancement

#380 Add lifecycle sidecar to mesh gateway
  templates/mesh-gateway-deployment.yaml
  test/unit/mesh-gateway-deployment.bats
Labels: area/multi-dc, bug

#388 Support LoadBalancerAddress for mesh gateways
  templates/mesh-gateway-clusterrole.yaml
  templates/mesh-gateway-deployment.yaml
  test/unit/mesh-gateway-clusterrole.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/mesh-gateway-service.bats
  values.yaml
Labels: area/multi-dc, enhancement

#375 Support auto-encrypt
  templates/_helpers.tpl
  templates/client-daemonset.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-deployment.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-statefulset.yaml
  templates/sync-catalog-deployment.yaml
  templates/tests/test-runner.yaml
  test/unit/client-daemonset.bats
  test/unit/client-snapshot-agent-deployment.bats
  test/unit/connect-inject-deployment.bats
  test/unit/helpers.bats
  test/unit/mesh-gateway-deployment.bats
  test/unit/server-statefulset.bats
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: theme/tls

#394 Remove use of -init-type=sync as it has no effect
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-deployment.yaml
  templates/enterprise-license-job.yaml
  templates/mesh-gateway-deployment.yaml
  templates/sync-catalog-deployment.yaml
  test/unit/mesh-gateway-deployment.bats
Labels: enhancement

#395 Allow setting items for server.extraVolumes
  templates/server-statefulset.yaml
  test/unit/server-statefulset.bats
  values.yaml
Labels: area/chart-only, enhancement
