Repository hashicorp/consul-helm, pull requests merged in 2020-06, with the labels that each got.

#480 Add component label to all services
  templates/dns-service.yaml
  templates/server-service.yaml
  templates/ui-service.yaml
Labels: area/chart-only, enhancement

#496 add support for client host networking and tests
  templates/client-daemonset.yaml
  templates/client-podsecuritypolicy.yaml
  test/unit/client-daemonset.bats
  test/unit/client-podsecuritypolicy.bats
  values.yaml
Labels: enhancement, theme/host-network

#335 Add Affinity and Tolerations to Inject and Sync
  templates/connect-inject-deployment.yaml
  templates/sync-catalog-deployment.yaml
  test/unit/connect-inject-deployment.bats
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: area/connect, area/sync, enhancement

#495 Update helm test to validate successful installation
  templates/tests/test-runner.yaml
Labels: area/chart-only, bug

#470 Support default sidecar proxy resources
  templates/connect-inject-deployment.yaml
  test/unit/connect-inject-deployment.bats
  values.yaml
Labels: enhancement

#469 Fully remove support for global.bootstrapACLs
  templates/NOTES.txt
  templates/client-clusterrole.yaml
  templates/client-daemonset.yaml
  templates/client-snapshot-agent-clusterrole.yaml
  templates/client-snapshot-agent-deployment.yaml
  templates/connect-inject-authmethod-clusterrole.yaml
  templates/connect-inject-authmethod-clusterrolebinding.yaml
  templates/connect-inject-authmethod-serviceaccount.yaml
  templates/connect-inject-clusterrole.yaml
  templates/connect-inject-deployment.yaml
  templates/create-federation-secret-job.yaml
  templates/create-federation-secret-role.yaml
  templates/enterprise-license-clusterrole.yaml
  templates/enterprise-license-job.yaml
  templates/ingress-gateways-deployment.yaml
  templates/ingress-gateways-role.yaml
  templates/mesh-gateway-clusterrole.yaml
  templates/mesh-gateway-deployment.yaml
  templates/server-acl-init-cleanup-clusterrole.yaml
  templates/server-acl-init-cleanup-clusterrolebinding.yaml
  templates/server-acl-init-cleanup-job.yaml
  templates/server-acl-init-cleanup-podsecuritypolicy.yaml
  templates/server-acl-init-cleanup-serviceaccount.yaml
  templates/server-acl-init-clusterrole.yaml
  templates/server-acl-init-clusterrolebinding.yaml
  templates/server-acl-init-job.yaml
  templates/server-acl-init-podsecuritypolicy.yaml
  templates/server-acl-init-serviceaccount.yaml
  templates/server-config-configmap.yaml
  templates/sync-catalog-clusterrole.yaml
  templates/sync-catalog-deployment.yaml
  templates/terminating-gateways-deployment.yaml
  templates/terminating-gateways-role.yaml
  test/unit/helpers.bats
  test/unit/server-acl-init-job.bats
  test/unit/sync-catalog-deployment.bats
  values.yaml
Labels: area/chart-only

#511 remove enterprise license cluster roles
  templates/enterprise-license-role.yaml
  templates/enterprise-license-rolebinding.yaml
  test/unit/enterprise-license-role.bats
  test/unit/enterprise-license-rolebinding.bats
Labels: enhancement, theme/consul-namespaces

#506 remove unnecessary server ClusterRoles
  templates/server-acl-init-cleanup-role.yaml
  templates/server-acl-init-cleanup-rolebinding.yaml
  templates/server-acl-init-role.yaml
  templates/server-acl-init-rolebinding.yaml
  templates/server-role.yaml
  templates/server-rolebinding.yaml
  test/unit/server-acl-init-cleanup-role.bats
  test/unit/server-acl-init-cleanup-rolebinding.bats
  test/unit/server-acl-init-role.bats
  test/unit/server-acl-init-rolebinding.bats
  test/unit/server-role.bats
  test/unit/server-rolebinding.bats
Labels: enhancement, theme/consul-namespaces

#505 Remove unnecessary client ClusterRoles
  templates/client-role.yaml
  templates/client-rolebinding.yaml
  templates/client-snapshot-agent-role.yaml
  templates/client-snapshot-agent-rolebinding.yaml
  test/unit/client-role.bats
  test/unit/client-rolebinding.bats
  test/unit/client-snapshot-agent-role.bats
  test/unit/client-snapshot-agent-rolebinding.bats
Labels: enhancement, theme/consul-namespaces

#498 Do not use ClusterRole/Bindings unnecessarily for tls-init templates
  templates/tls-init-cleanup-role.yaml
  templates/tls-init-cleanup-rolebinding.yaml
  templates/tls-init-role.yaml
  templates/tls-init-rolebinding.yaml
  test/unit/tls-init-cleanup-role.bats
  test/unit/tls-init-cleanup-rolebinding.bats
  test/unit/tls-init-role.bats
  test/unit/tls-init-rolebinding.bats
Labels: enhancement, theme/consul-namespaces

#336 Use namespace environment variable instead of helm
  templates/tls-init-job.yaml
Labels: enhancement
