Repository hashicorp/consul-helm, pull requests merged in 2020-10, with the labels that each got.

#600 Openshift support
  .circleci/config.yml
  templates/client-role.yaml
  templates/client-securitycontextconstraints.yaml
  templates/create-federation-secret-job.yaml
  templates/ingress-gateways-deployment.yaml
  templates/server-acl-init-cleanup-job.yaml
  templates/server-acl-init-job.yaml
  templates/server-statefulset.yaml
  templates/terminating-gateways-deployment.yaml
  templates/tls-init-cleanup-job.yaml
  templates/tls-init-job.yaml
  test/acceptance/framework/config.go
  test/acceptance/framework/config_test.go
  test/acceptance/framework/flags.go
  test/acceptance/helpers/helpers.go
  test/acceptance/tests/basic/basic_test.go
  test/acceptance/tests/consul-dns/consul_dns_test.go
  test/acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
  test/acceptance/tests/terminating-gateway/terminating_gateway_test.go
  test/docker/Test.dockerfile
  test/unit/client-role.bats
  test/unit/client-securitycontextconstraints.bats
  test/unit/server-statefulset.bats
  values.yaml
Labels: enhancement, theme/openshift

#631 Update proxy-defaults config type to object
  templates/crd-proxydefaults.yaml
  test/acceptance/tests/fixtures/crds/proxydefaults.yaml
Labels: bug, theme/crds

#637 Openshift: Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#638 Add annotation to prevent controller from getting connect injected
  templates/controller-deployment.yaml
Labels: bug, theme/crds

#644 Fix controller openshift tests; fix flakey tests
  templates/_helpers.tpl
  templates/webhook-cert-manager-deployment.yaml
  test/acceptance/framework/consul_cluster.go
  test/acceptance/helpers/helpers.go
Labels: theme/openshift

#615 Health checks base
  .circleci/config.yml
  templates/connect-inject-clusterrole.yaml
  templates/connect-inject-deployment.yaml
  test/acceptance/tests/connect/health_checks_test.go
  test/acceptance/tests/fixtures/bases/static-client/deployment.yaml
  test/acceptance/tests/fixtures/cases/static-server-hc/kustomization.yaml
  test/acceptance/tests/fixtures/cases/static-server-hc/patch.yaml
  test/unit/connect-inject-clusterrole.bats
  test/unit/connect-inject-deployment.bats
  values.yaml
Labels: enhancement, theme/health-checks

#649 Bump controller memory request/limit for OpenShift
  test/acceptance/framework/consul_cluster.go
  test/unit/controller-deployment.bats
  values.yaml
Labels: bug, theme/crds, theme/openshift

#651 add support for consul-k8s health checks controller for service mesh
  templates/connect-inject-clusterrole.yaml
  templates/connect-inject-deployment.yaml
  test/acceptance/go.mod
  test/acceptance/go.sum
  test/acceptance/tests/connect/health_checks_test.go
  test/acceptance/tests/fixtures/bases/static-client/deployment.yaml
  test/acceptance/tests/fixtures/cases/static-server-hc/kustomization.yaml
  test/acceptance/tests/fixtures/cases/static-server-hc/patch.yaml
  test/unit/connect-inject-clusterrole.bats
  test/unit/connect-inject-deployment.bats
  values.yaml
Labels: enhancement, theme/health-checks

#654 support new versions of timeout in ent-license
  templates/enterprise-license-job.yaml
Labels: area/chart-only, bug

#661 acceptance-tests: expect conn reset by peer errors when health checks are failing
  test/acceptance/helpers/helpers.go
  test/acceptance/tests/connect/connect_inject_namespaces_test.go
  test/acceptance/tests/connect/connect_inject_test.go
  test/acceptance/tests/connect/health_checks_test.go
  test/acceptance/tests/ingress-gateway/ingress_gateway_namespaces_test.go
  test/acceptance/tests/ingress-gateway/ingress_gateway_test.go
  test/acceptance/tests/mesh-gateway/mesh_gateway_test.go
  test/acceptance/tests/terminating-gateway/terminating_gateway_namespaces_test.go
  test/acceptance/tests/terminating-gateway/terminating_gateway_test.go
  test/terraform/gke/main.tf
Labels: bug, theme/acceptance-tests, theme/health-checks

#662 Add age and labels to CRDs
  templates/crd-proxydefaults.yaml
  templates/crd-servicedefaults.yaml
  templates/crd-serviceintentions.yaml
  templates/crd-serviceresolvers.yaml
  templates/crd-servicerouters.yaml
  templates/crd-servicesplitters.yaml
  test/terraform/gke/main.tf
Labels: enhancement, theme/crds
