Repository hashicorp/consul-helm, pull requests merged in 2021-01, with the labels that each got.

#764 Remove preStop hook that calls consul leave from Consul servers
  CHANGELOG.md
  templates/server-statefulset.yaml
Labels: bug

#790 tls-init and tls-init-cleanup jobs use GA RBAC API instead of beta
  CHANGELOG.md
  templates/tls-init-cleanup-role.yaml
  templates/tls-init-cleanup-rolebinding.yaml
  templates/tls-init-role.yaml
  templates/tls-init-rolebinding.yaml
Labels: bug

#612 Add ability to set extra labels on client pods
  templates/client-daemonset.yaml
  test/unit/client-daemonset.bats
  values.yaml
Labels: area/chart-only, enhancement

#791 Provide a deterministic host-based node ID for the Consul clients.
  CHANGELOG.md
  templates/client-daemonset.yaml
Labels: bug

#777 Run acceptance tests against kind v1.19.4; add a nightly run for kind v1.20.2
  .circleci/config.yml
Labels: area/builds, theme/acceptance-tests
