Repository hashicorp/consul-helm, pull requests merged in 2021-03, with the labels that each got.

#849 Add last synced time to CRDs
  CHANGELOG.md
  templates/crd-ingressgateways.yaml
  templates/crd-proxydefaults.yaml
  templates/crd-servicedefaults.yaml
  templates/crd-serviceintentions.yaml
  templates/crd-serviceresolvers.yaml
  templates/crd-servicerouters.yaml
  templates/crd-servicesplitters.yaml
  templates/crd-terminatinggateways.yaml
Labels: enhancement, theme/crds

#858 Acceptance tests fixes
  .circleci/config.yml
  test/acceptance/tests/metrics/metrics_test.go
  test/terraform/aks/main.tf
  test/terraform/aks/variables.tf
  test/terraform/eks/main.tf
  test/terraform/eks/variables.tf
  test/terraform/gke/main.tf
  test/terraform/gke/variables.tf
Labels: area/builds, theme/acceptance-tests

#880 use non-root folder to create apply-license script
  templates/enterprise-license-job.yaml
Labels: bug
